Add requirement Section in README and Fix Makefile
mattcurrie/mgbdis pull request #27
Opened 2022-03-12 16:38 UTC by iAmG-r00t

- Added a requirement section for a new user.
- The makefile generated contained a wrong command: `md5` instead of `md5sum`.

2022-03-12 16:42 UTC, ISSOtm requested changes

2022-03-12 16:42 UTC, ISSOtm commented on README.md
> +To be able to use this tool you will require to install the [Rendex Game Boy Development System (RGBDS)](https://github.com/gbdev/rgbds) tool.
```suggestion
The assembly files generated by mgbdis are designed to be assembled with [RGBDS](https://rgbds.gbdev.io).
```

I think this phrasing is a little clearer. Additionally, it's better to link to the official website, as it contains per-OS install instructions—`make install` won't work on Windows out of the box, for example, and other OSes don't use `apt-get` and may require different packages.

2022-03-12 16:42 UTC, ISSOtm commented on mgbdis.py
> +        f.write('\tmd5sum $@\n\n')
This is correct on my Linux box, but @mattcurrie might be able to confirm whether that's the case on macOS?

2022-03-12 19:37 UTC, iAmG-r00t commented on mgbdis.py
> +        f.write('\tmd5sum $@\n\n')
Yep on macOS to get md5 HASH one would use `md5`, a fix could be a function to check the OS if it's Linux use `md5sum` else if its macOS use `md5`

2022-03-12 20:15 UTC, ISSOtm commented on mgbdis.py
> +        f.write('\tmd5sum $@\n\n')
Alternatively, `if which md5sum &>/dev/null; then md5sum $@; else md5 $@; fi` to detect the presence of the tool itself regardless of OS.

2022-03-12 21:19 UTC, mattcurrie commented on mgbdis.py
> +        f.write('\tmd5sum $@\n\n')
Yeah, I prefer the detection approach as it makes the makefile portable

2022-03-12 23:10 UTC, iAmG-r00t commented on mgbdis.py
> +        f.write('\tmd5sum $@\n\n')
Okay found a solution, let me update then @mattcurrie you check if it works properly on macOS

2022-03-12 23:41 UTC, iAmG-r00t commented on mgbdis.py
> +        f.write('\tmd5sum $@\n\n')
@ISSOtm kindly review and check if the changes are okay and @mattcurrie check if the command detection is portable.

2022-03-13 01:16 UTC, mattcurrie commented on mgbdis.py
> +        f.write('\tmd5sum $@\n\n')
@iAmG-r00t I've just tested the detection command in the makefile and it works fine for me on macOS.

2022-03-13 01:17 UTC, iAmG-r00t commented on mgbdis.py
> +        f.write('\tmd5sum $@\n\n')
Okay then you should proceed and push.

2022-03-13 09:05 UTC, ISSOtm approved these changes

2022-03-13 19:35 UTC, mattcurrie commented on mgbdis.py
> +            f.write('\tmd5sum $@\n\n')
```suggestion
        f.write('\t@if which md5sum &>/dev/null; then md5sum $@; else md5 $@; fi\n\n')
```

2022-03-13 19:36 UTC, mattcurrie commented on mgbdis.py
> +from shutil import which
```suggestion
```

2022-03-13 19:38 UTC, mattcurrie commented
Thanks @iAmG-r00t and @ISSOtm

2022-03-13 19:39 UTC, merged