Escape double quote string
mattcurrie/mgbdis pull request #31
Opened 2023-08-19 18:32 UTC by tommylau-exe

Currently, string data can be output incorrectly if it contains characters that [rgbasm notes should be escaped](https://rgbds.gbdev.io/docs/v0.6.1/rgbasm.5#String_expressions) (namely `"`, `\`, `{`, `}`). Just made a quick fix 👍

Love the project btw!

2023-08-20 00:36 UTC, ISSOtm requested changes
Oh yeah, the funny oversight of round-tripping. Thanks for the PR!

2023-08-20 00:36 UTC, ISSOtm commented on mgbdis.py
> +                escapeChars = {'"', '\\', '{', '}'}
I feel like this should either be a constant (I think the Pythonic way is to make the name all uppercase?), or directly `if chr(byte) in ['"', '\\', '{', '}']:`.

I'm also unsure of how this works with braces—isn't that supposed to be dict syntax?

2023-08-20 00:50 UTC, tommylau-exe commented on mgbdis.py
> +                escapeChars = {'"', '\\', '{', '}'}
Good call- I think inline would be good actually since there's only 4 characters to worry about. I'll update it

Admittedly my Python is a bit rusty, but I believe this is set syntax. Putting them in an array is functionally equivalent here with only 4 elements, I just thought a set was more fitting here. Let me know what you think

2023-08-20 01:03 UTC, ISSOtm commented on mgbdis.py
> +                escapeChars = {'"', '\\', '{', '}'}
TIL about set syntax; that does sound more appropriate here.

2023-08-20 01:03 UTC, ISSOtm approved these changes

2023-08-26 00:52 UTC, mattcurrie commented
Thanks both!

2023-08-26 00:52 UTC, mattcurrie approved these changes

2023-08-26 00:52 UTC, merged